@startuml

package splitter {
    class Ausgaben {
        - name: String
        - ausgabe: Double
        + Ausgaben(name: String, ausgabe: Double)
        + getName(): String
        + getAusgabe(): Double
        + toString(): String
    }

    class AusgabenVerwaltung {
        - ausgabenListe: List<Ausgaben>
        + AusgabenVerwaltung()
        + addAusgaben(ausgaben: Ausgaben): void
        + addAusgabenInArrayListe(a: List<Ausgaben>): void
        + removeAusgabeVonListe(index: int): void
        + getAusgaben(): List<Ausgaben>
    }

    class AusgabenRechner {
        - ausgaben: List<Ausgaben>
        + AusgabenRechner(ausgaben: List<Ausgaben>)
        + summiereEinzelneAusgaben(): Map<String, Double>
        + getGesamtsumme(): Double
        + getAnzahlPersonen(): int
        + rechneAverageDebtPerPerson(): double
        + erstelleSchuldenListe(): List<String>
    }

    class CSVReader {
        + CSVReader()
        + readAusgaben(filepath: String): List<Ausgaben>
        - parseAusgabenVonCSV(line: String): Ausgaben
    }

    class Main {
        + main(args: String[]): void
    }

    AusgabenVerwaltung ..> Ausgaben : "1" contains > "1"
    AusgabenRechner --> Ausgaben : "1" uses > "1"
    Main --> CSVReader : "1" --> "1"
    Main --> AusgabenVerwaltung : "1" --> "1"
    Main --> AusgabenRechner : "1" --> "1"
    CSVReader --> Ausgaben : "1" uses > "1"

}

@enduml
